# RoboMimic Environment Configuration
name: robomimic
task_name: Square

image_size: 84
max_episode_steps: 400
action_dim: 7
obs_dim: 9

action_horizon: 16
default_denoise_steps: 10

budgets:
  simple:
    num_denoise_steps: 2
    action_horizon: 16
  medium:
    num_denoise_steps: 5
    action_horizon: 12
  complex:
    num_denoise_steps: 10
    action_horizon: 8
